// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkPCBwzQeXYYGUtq6_sqZKfi6a6At5jaw',
    appId: '1:881972389573:web:cf0537aa37acb5254d72ac',
    messagingSenderId: '881972389573',
    projectId: 'neuralmedicsmobileapp',
    authDomain: 'neuralmedicsmobileapp.firebaseapp.com',
    storageBucket: 'neuralmedicsmobileapp.firebasestorage.app',
    measurementId: 'G-35W6MVJST1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxWbj7eJE36uSYgnYx7BSAIeCindkA02I',
    appId: '1:881972389573:android:23e418fd849115364d72ac',
    messagingSenderId: '881972389573',
    projectId: 'neuralmedicsmobileapp',
    storageBucket: 'neuralmedicsmobileapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUE8JoLBjKw1n8EzbyK0DZy9JKC1SkaOk',
    appId: '1:881972389573:ios:885d698b03f3f5a84d72ac',
    messagingSenderId: '881972389573',
    projectId: 'neuralmedicsmobileapp',
    storageBucket: 'neuralmedicsmobileapp.firebasestorage.app',
    iosBundleId: 'com.example.neuralmedicsmobileapp',
  );

}